IMG_WIDTH = 150
IMG_HEIGHT = 150

provincias = {
    0: "San Luis",
    1: "Catamarca",
    2: "La Rioja",
    3: "Argentina",
    4: "Chubut",
    5: "Mendoza",
    6: "Santa Cruz",
    7: "Salta",
    8: "Rio Negro",
    9: "Tucuman",
    10: "Chaco",
    11: "Corrientes",
    12: "San Juan",
    13: "Santa Fe",
    14: "Córdoba",
    15: "Santiado del Estero",
    16: "La Pampa",
    17: "Misiones",
    18: "Neuquen",
    19: "Tierra del Fuego",
    20: "Entre Rios",
    21: "Buenos Aires",
    22: "Jujuy",
    23: "Formosa",
    24: "CABA",
}
