IMG_WIDTH = 150
IMG_HEIGHT = 150

provincias = {
    0: "San Luis",
    1: "Catamarca",
    2: "La Rioja",
    3: "Argentina",
    4: "Chubut",
    5: "Mendoza",
    6: "Santa Cruz",
    7: "Salta",
    8: "Rio Negro",
    9: "Tucuman",
    10: "Chaco",
    11: "Corrientes",
    12: "San Juan",
    13: "Santa Fe",
    14: "Córdoba",
    15: "Santiado del Estero",
    16: "La Pampa",
    17: "Misiones",
    18: "Neuquen",
    19: "Tierra del Fuego",
    20: "Entre Rios",
    21: "Buenos Aires",
    22: "Jujuy",
    23: "Formosa",
    24: "CABA",
}

filenames = {
    0: "sanluisSegmented.jpg",
    1: "catamarcaSegmented.jpg",
    2: "lariojaSegmented.jpg",
    3: "argentinaSegmented.jpg",
    4: "chubutSegmented.jpg",
    5: "mendozaSegmented.jpg",
    6: "santacruzSegmented.jpg",
    7: "saltaSegmented.jpg",
    8: "rionegroSegmented.jpg",
    9: "tucumanSegmented.jpg",
    10: "chacoSegmented.jpg",
    11: "corrientesSegmented.jpg",
    12: "sanjuanSegmented.jpg",
    13: "santafeSegmented.jpg",
    14: "cordobaSegmented.jpg",
    15: "santiagoSegmented.jpg",
    16: "lapampaSegmented.jpg",
    17: "misionesSegmented.jpg",
    18: "neuquenSegmented.jpg",
    19: "tierradelfuegoSegmented.jpg",
    20: "entreriosSegmented.jpg",
    21: "buenosairesSegmented.jpg",
    22: "jujuySegmented.jpg",
    23: "formosaSegmented.jpg",
    24: "cabaSegmented.jpg",
}
